// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Js_math = require("bs-platform/lib/js/js_math.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Util$ReactHooksTemplate = require("../Util.bs.js");
var SharedTypes$ReactHooksTemplate = require("../SharedTypes.bs.js");

function buildFleet(param) {
  var carrier = /* record */[
    /* damage */0,
    /* shipType : Carrier */0,
    /* isSunk */false,
    /* shipLength */5,
    /* coordinates */Caml_array.caml_make_vect(5, /* tuple */[
          -1,
          -1
        ])
  ];
  var battleship = /* record */[
    /* damage */0,
    /* shipType : Battleship */1,
    /* isSunk */false,
    /* shipLength */4,
    /* coordinates */Caml_array.caml_make_vect(4, /* tuple */[
          -1,
          -1
        ])
  ];
  var submarine = /* record */[
    /* damage */0,
    /* shipType : Submarine */3,
    /* isSunk */false,
    /* shipLength */3,
    /* coordinates */Caml_array.caml_make_vect(3, /* tuple */[
          -1,
          -1
        ])
  ];
  var destroyer = /* record */[
    /* damage */0,
    /* shipType : Destroyer */2,
    /* isSunk */false,
    /* shipLength */3,
    /* coordinates */Caml_array.caml_make_vect(3, /* tuple */[
          -1,
          -1
        ])
  ];
  var patrolBoat = /* record */[
    /* damage */0,
    /* shipType : PatrolBoat */4,
    /* isSunk */false,
    /* shipLength */2,
    /* coordinates */Caml_array.caml_make_vect(2, /* tuple */[
          -1,
          -1
        ])
  ];
  return /* :: */[
          carrier,
          /* :: */[
            battleship,
            /* :: */[
              submarine,
              /* :: */[
                destroyer,
                /* :: */[
                  patrolBoat,
                  /* [] */0
                ]
              ]
            ]
          ]
        ];
}

function updateBoardWithShipCoordinates(board, ship) {
  return $$Array.map((function (param) {
                return Caml_array.caml_array_set(Caml_array.caml_array_get(board, param[0]), param[1], /* Ship */1);
              }), ship[/* coordinates */4]);
}

function randomlyPlaceShips(board, fleet) {
  return List.map((function (ship) {
                var randomX = Js_math.floor(SharedTypes$ReactHooksTemplate.boardSize * Math.random());
                var randomY = Js_math.floor(SharedTypes$ReactHooksTemplate.boardSize * Math.random());
                var randomDirection = Js_math.floor(2 * Math.random());
                while(!Util$ReactHooksTemplate.isLegalPlacement(board, randomX, randomY, randomDirection, ship[/* shipLength */3])) {
                  randomX = Js_math.floor(SharedTypes$ReactHooksTemplate.boardSize * Math.random());
                  randomY = Js_math.floor(SharedTypes$ReactHooksTemplate.boardSize * Math.random());
                  randomDirection = Js_math.floor(2 * Math.random());
                };
                var x = randomX;
                var y = randomY;
                var direction = randomDirection;
                ship[/* coordinates */4] = Util$ReactHooksTemplate.getCoordinatesForShip(ship, x, y, direction);
                return updateBoardWithShipCoordinates(board, ship);
              }), fleet);
}

function initialState(param) {
  var humanFleet = buildFleet(/* () */0);
  var aiFleet = buildFleet(/* () */0);
  var humanBoard = $$Array.make_matrix(SharedTypes$ReactHooksTemplate.boardSize, SharedTypes$ReactHooksTemplate.boardSize, /* Empty */0);
  var aiBoard = $$Array.make_matrix(SharedTypes$ReactHooksTemplate.boardSize, SharedTypes$ReactHooksTemplate.boardSize, /* Empty */0);
  randomlyPlaceShips(humanBoard, humanFleet);
  randomlyPlaceShips(aiBoard, aiFleet);
  return /* record */[
          /* humanBoard */humanBoard,
          /* humanFleet */humanFleet,
          /* aiBoard */aiBoard,
          /* aiFleet */aiFleet,
          /* turnState : Playing */Block.__(0, [/* Human */0])
        ];
}

var boardContext = React.createContext(initialState(/* () */0));

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = boardContext.Provider;

var BoardProvider = /* module */[
  /* makeProps */makeProps,
  /* make */make
];

exports.buildFleet = buildFleet;
exports.updateBoardWithShipCoordinates = updateBoardWithShipCoordinates;
exports.randomlyPlaceShips = randomlyPlaceShips;
exports.initialState = initialState;
exports.boardContext = boardContext;
exports.BoardProvider = BoardProvider;
/* boardContext Not a pure module */
