// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var BoardTile$ReactHooksTemplate = require("./BoardTile.bs.js");

function BoardRow(Props) {
  var row = Props.row;
  var index = Props.index;
  var boardOwner = Props.boardOwner;
  return React.createElement("div", {
              className: "board-row"
            }, $$Array.mapi((function (ind, tile) {
                    var id = String(index) + String(ind);
                    return React.createElement(BoardTile$ReactHooksTemplate.make, {
                                x: String(index),
                                y: String(ind),
                                tile: tile,
                                boardOwner: boardOwner,
                                key: id
                              });
                  }), row));
}

var make = BoardRow;

exports.make = make;
/* react Not a pure module */
