// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var BoardTile$ReactHooksTemplate = require("./BoardTile.bs.js");
var AppContext$ReactHooksTemplate = require("./AppContext.bs.js");

function BoardRow(Props) {
  var index = Props.index;
  var boardOwner = Props.boardOwner;
  var onTileClick = Props.onTileClick;
  var gameState = React.useContext(AppContext$ReactHooksTemplate.boardContext);
  var board = boardOwner ? gameState[/* aiBoard */2] : gameState[/* humanBoard */0];
  return React.createElement("div", {
              className: "board-row"
            }, $$Array.mapi((function (ind, tile) {
                    return React.createElement(BoardTile$ReactHooksTemplate.make, {
                                x: String(index),
                                y: String(ind),
                                boardOwner: boardOwner,
                                onTileClick: onTileClick,
                                key: String(index) + String(ind)
                              });
                  }), Caml_array.caml_array_get(board, index)));
}

var make = BoardRow;

exports.make = make;
/* react Not a pure module */
