// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function BoardTile(Props) {
  var x = Props.x;
  var y = Props.y;
  var tile = Props.tile;
  Props.boardOwner;
  var tmp;
  switch (tile) {
    case 0 : 
        tmp = "";
        break;
    case 1 : 
        tmp = " 🚢 ";
        break;
    case 2 : 
        tmp = " 💨 ";
        break;
    case 3 : 
        tmp = " 🔥 ";
        break;
    case 4 : 
        tmp = " ☠ ";
        break;
    
  }
  return React.createElement("div", {
              className: "board-tile",
              x: x,
              y: y
            }, tmp);
}

var make = BoardTile;

exports.make = make;
/* react Not a pure module */
