// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var AppContext$ReactHooksTemplate = require("./AppContext.bs.js");

function GameOver(Props) {
  var turnState = Props.turnState;
  var setGameState = Props.setGameState;
  var click = function (param) {
    return Curry._1(setGameState, (function (param) {
                  return AppContext$ReactHooksTemplate.initialState(/* () */0);
                }));
  };
  var tmp;
  tmp = turnState.tag ? (
      turnState[0] ? React.createElement("h1", {
              className: "title-color game-title"
            }, "YOU LOST!") : React.createElement("h1", {
              className: "title-color game-title"
            }, "YOU WON!")
    ) : React.createElement("div", undefined);
  return React.createElement("div", {
              className: "gameover-container"
            }, tmp, React.createElement("button", {
                  className: "button-xlarge",
                  id: "replay-btn",
                  onClick: click
                }, React.createElement("span", {
                      className: "title-color"
                    }, "Play Again")));
}

var make = GameOver;

exports.make = make;
/* react Not a pure module */
