// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Board$ReactHooksTemplate = require("./components/Board.bs.js");

((require('./game.css')));

function initialGameState(param) {
  return /* record */[
          /* humanBoard */$$Array.make_matrix(10, 10, /* Empty */0),
          /* aiBoard */$$Array.make_matrix(10, 10, /* Empty */0),
          /* gameState : Playing */Block.__(0, [/* Human */0])
        ];
}

function Game(Props) {
  var match = React.useState((function () {
          return initialGameState(/* () */0);
        }));
  var state = match[0];
  return React.createElement("div", {
              className: "game-container"
            }, React.createElement("h2", {
                  className: "board-title"
                }, "Warship"), React.createElement(Board$ReactHooksTemplate.make, {
                  state: state,
                  boardOwner: /* Human */0,
                  boardArray: state[/* humanBoard */0]
                }), React.createElement(Board$ReactHooksTemplate.make, {
                  state: state,
                  boardOwner: /* AI */1,
                  boardArray: state[/* aiBoard */1]
                }));
}

var make = Game;

exports.initialGameState = initialGameState;
exports.make = make;
/*  Not a pure module */
