// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var boardSize = 10;

var directionVertical = 0;

var directionHorizontal = 1;

exports.boardSize = boardSize;
exports.directionVertical = directionVertical;
exports.directionHorizontal = directionHorizontal;
/* No side effect */
