// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var SharedTypes$ReactHooksTemplate = require("./SharedTypes.bs.js");

function isLegalPlacement(board, x, y, direction, shipLength) {
  var validPlacement = /* record */[/* contents */false];
  if (direction === SharedTypes$ReactHooksTemplate.directionVertical) {
    validPlacement[0] = (x + shipLength | 0) <= SharedTypes$ReactHooksTemplate.boardSize;
  } else {
    validPlacement[0] = (y + shipLength | 0) <= SharedTypes$ReactHooksTemplate.boardSize;
  }
  if (validPlacement[0]) {
    for(var index = 0 ,index_finish = shipLength - 1 | 0; index <= index_finish; ++index){
      if (validPlacement[0]) {
        if (direction === SharedTypes$ReactHooksTemplate.directionVertical) {
          validPlacement[0] = Caml_array.caml_array_get(Caml_array.caml_array_get(board, x + index | 0), y) === /* Empty */0;
        } else {
          validPlacement[0] = Caml_array.caml_array_get(Caml_array.caml_array_get(board, x), y + index | 0) === /* Empty */0;
        }
      }
      
    }
  }
  return validPlacement;
}

exports.isLegalPlacement = isLegalPlacement;
/* No side effect */
